modLoader="javafml" #mandatory

loaderVersion="[47,)" #mandatory

license="GNU General Public License v3.0"

[[mods]] #mandatory

modId="starrynights" #mandatory

version="1.0.0" #mandatory

displayName="Starry Nights" #mandatory

authors="Pickle_Face5" #optional

#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description='''
Simple Skybox improvement mod.
'''

[[dependencies.starrynights]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.starrynights]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"